### ISSUE TITLE
 Missing helper: "greenBright" on any gh gif command

### ISSUE THREAD

**Issue by maxandersen** [node-gh/gh-gif#11]
no matter what gh gif command I run I get something like this error:

```
gh gif 417 --reaction happy                                             ⏎ ⬆ ✭

/usr/local/lib/node_modules/gh/node_modules/handlebars/dist/cjs/handlebars/base.js:86
      throw new _Exception2['default']('Missing helper: "' + arguments[argumen
            ^
Error: Missing helper: "greenBright"
    at Object.<anonymous> (/usr/local/lib/node_modules/gh/node_modules/handlebars/dist/cjs/handlebars/base.js:86:13)
    at Object.eval (eval at createFunctionContext (/usr/local/lib/node_modules/gh/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:7:80)
    at ret (/usr/local/lib/node_modules/gh/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/usr/local/lib/node_modules/gh/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.logger.compileTemplate (/usr/local/lib/node_modules/gh/lib/logger.js:110:37)
    at Object.logger.logTemplate (/usr/local/lib/node_modules/gh/lib/logger.js:114:24)
    at Gif.run (/usr/local/lib/node_modules/gh-gif/bin/gif.js:62:16)
    at /usr/local/lib/node_modules/gh/lib/cmd.js:199:34
    at Array.forEach (native)
    at /usr/local/lib/node_modules/gh/lib/cmd.js:190:25
```

**Comment by maxandersen** [comment]
I updated to 0.3.3 and that fixed it.
